In [4]:
import jax
import jax.numpy as jnp

In [7]:
# - pastObservationStack:      (stackSize, observationSize)
# - pastObservationTimestamps: (stackSize, 1)
# - pastActions:               (stackSize, actionSpaceSize)
# - pastMask:                  (stackSize, 1)
# - currentObservation:        (observationSize)
stackSize = 2
observationSize = 10
actionSpaceSize = 3

pastObservationStack = jnp.zeros((stackSize, observationSize))
pastObservationTimestamps = jnp.zeros((stackSize, 1))
pastActions = jnp.zeros((stackSize, actionSpaceSize))
pastMask = jnp.zeros((stackSize, 1))

print(f'pastObservationStack: {pastObservationStack.shape}')
print(f'pastObservationTimestamps: {pastObservationTimestamps.shape}')
print(f'pastActions: {pastActions.shape}')
print(f'pastMask: {pastMask.shape}')

concatted = jnp.concat([pastObservationStack, pastObservationTimestamps, pastActions], axis=1)
print(f'concatted: {concatted.shape}')


pastObservationStack: (2, 10)
pastObservationTimestamps: (2, 1)
pastActions: (2, 3)
pastMask: (2, 1)
concatted: (2, 14)


In [13]:
x = jnp.array([[1,2], [2,3], [3,4]])
y = jnp.array([[1], [1], [1]])
res = jnp.concat([x,y], axis=1)
print(res)

jnp.concat(res, axis=0)

x = jnp.ones((2,3,4))
print(x)
x = jnp.concat(x, axis=0)
print(x)


[[1 2 1]
 [2 3 1]
 [3 4 1]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
